<main>

    <div>
        <h1> Présentation </h1>
        <p>"Explorez le monde à moto : Votre aventure commence ici, grâce à notre service de location entre passionnés !"</p>

    </div>

    <div class="carousel">
        <img src="public/images/er6.jpg" alt="er6">
        <img src="public/images/mt09.jpg" alt="mt09">
    </div>

    <div class="container">
        <h2>Présentation : Service de Location de Moto entre Particuliers</h2>
        <p>Bonjour à tous les passionnés de deux-roues et les aventuriers de la route ! Nous sommes ravis de vous présenter notre tout nouveau service de location de moto entre particuliers. Si vous êtes à la recherche d'une expérience unique, flexible et excitante pour explorer les routes et les paysages à moto, vous êtes au bon endroit.</p>


        <h2>Pourquoi choisir notre service de location de moto entre particuliers ?</h2>
        <ol>
            <li><strong>Diversité de Choix :</strong> Notre plateforme regroupe une variété de motos, des cruisers élégants aux sportives audacieuses, en passant par les tout-terrains robustes. Vous pouvez choisir la moto qui correspond le mieux à votre style de conduite et à vos préférences. </li>
            <li><strong>Économique :</strong> Louer une moto à un particulier est souvent plus économique que de passer par des agences de location traditionnelles. Vous pouvez trouver des tarifs compétitifs et négocier directement avec les propriétaires.</li>
            <li><strong>Flexibilité :</strong> Notre service vous offre la flexibilité de choisir la durée de location qui vous convient, que vous ayez besoin d'une moto pour une journée entière ou même plus longtemps.</li>
            <li><strong>Expérience Locale :</strong> Explorer une région à moto vous permet de vivre une expérience plus authentique. Vous pourrez découvrir des endroits hors des sentiers battus et vous immerger davantage dans la culture locale.</li>
            <li><strong>Communauté :</strong> En utilisant notre service, vous rejoignez une communauté de passionnés de moto. Vous pouvez partager des conseils, des itinéraires recommandés et même établir des liens avec d'autres amateurs de deux-roues.</li>
        </ol>


        <p>Prêt à vivre une aventure exceptionnelle sur deux roues ? Rejoignez notre communauté de location de moto entre particuliers dès aujourd'hui et découvrez la liberté de parcourir les routes à votre manière. Vivez la route, ressentez la passion !</p>

    </div>

</main>