<main>
    <section>
        <div>
            <form method="POST">
                <label for="commentaire">Votre avis</label>
                <textarea id="commentaire" name="commentaire" placeholder="Avis"></textarea>

                <label for="note">Note</label>
                <select id="note" name="note">
                    <option value="0">0</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                </select>

                <button type="submit" name="envoyerAvis">Envoyer</button>
            </form>
        </div>
    </section>
</main>
