<main>
    <section>
        <form method="POST">
            <label for="nom">Votre nom</label>
            <input type="text" id="nom" name="nom" placeholder="Votre nom" >

            <label for="pwd">Votre mot de passe</label>
            <input type="password" id="pwd" name="pwd" placeholder="Votre mot de passe" >

            <button name="connexion" type="submit">Se connecter</button>
        </form>
    </section>

    <section>
        <a href="index.php?page=inscription" aria-label="Inscription" target="_blank">Créer un compte</a>
    </section>
</main>
