<main>

    <h1>Formulaire d'ajout d'une moto</h1>
    <div>
        <form method="POST" enctype="multipart/form-data">

            <label for="marque">Marque</label>
            <input name="marque" type="text" placeholder="marque" value="<?= $data['moto']->getMarque() ?>" />

            <label for="modele">Modèle</label>
            <input name="modele" type="text" placeholder="modele" value="<?= $data['moto']->getModele() ?>" />

            <label for="categorie">catégorie</label>
            <select name="categorie">
                <option value="">Toutes les catégories</option>
                <option value="Sportive">Sportive</option>
                <option value="Roadster">Roadster</option>
                <option value="Trail">Trail</option>
                <option value="Routiere">Routiére</option>
                <option value="Cross">Cross</option>
                <option value="Scooter">Scooter</option>
            </select>

            <label for="annee">Année</label>
            <input name="annee" type="number" placeholder="annee" />

            <label for="bridee">Bridée ou non ?</label>
            <select name="bridee">
                <option value="">Bridage</option>
                <option value="oui">oui</option>
                <option value="non">non</option>
            </select>

            <label for="description">Descritpion</label>
            <textarea name="description" placeholder="description"></textarea>

            <label for="prix">Prix de la location</label>
            <input name="prix" type="number" placeholder="prix" />

            <label for="file">Format: jpg, png, jpeg Max :5Mo</label>
            <input type="file" name="file" id="imageFile">

            <button name="submit">Envoyer</button>
        </form>
    </div>
</main>