<header>
    
    <img src="public/images/Capture d'écran 2023-07-23 135802.png" alt="logo" >
    
     <h1> Vroom Moto</h1>
    <div>
     <?php if (isset($_SESSION['ID'])) { ?>
    <a href="index.php?page=disconnect">Déconnexion</a>
    <?php } else { ?>
    <a href="index.php?page=inscription">Inscription</a>
    <a href="index.php?page=connexion">Connexion</a>
    <?php } ?>
    </div>
</header>