<header>

    <img src="public/images/VROOM.png" alt="logo">

    <h1> LOCATION DE MOTO ENTRE PARTICULIERS</h1>

    <div class="bienvenue">
        <?php if ($user) { ?>
        <p>Bienvenue
            <?= $user->getNom() ?>
        </p>
        <a href="index.php?page=disconnect">Déconnexion</a>

        <?php } else { ?>

        <a href="index.php?page=connexion">Se connecter</a>

        <?php } ?>

    </div>

</header>