<html>
    <head>
        
    </head>
    <body>
        <form method="POST">
            <input type="text" name="nom" placeholder="Votre nom" />
             <input type="email" name="email" placeholder="Email" />
            <input type="password" name="pwd" placeholder="Votre mot de passe" />
            <input type="password" name="pwd2" placeholder="Re-tapez votre mot de passe" />
            <button name="subscribe">S'inscrire</button>
        </form>
    </body>
</html>