<main>
    <section>
        <h1>Mes motos</h1>
        <div class="moto-list">
            <?php
            if (isset($data['motos'])) {
                foreach ($data['motos'] as $moto) {
            ?>
                    <article class="moto-card">
                        <p><a href="index.php?page=moto&id=<?= htmlspecialchars($moto->getId()); ?>"><?= htmlspecialchars($moto->getModele()); ?></a></p>
                        <img src="<?= htmlspecialchars($moto->getImage()); ?>" alt="<?= htmlspecialchars($moto->getModele()); ?> Image" />
                    </article>
            <?php
                }
            }
            ?>
        </div>
    </section>
</main>
