<main>

    <?php
    if (isset($data['locations'])) {

    ?>
        <h1>Les locations de mes motos</h1>
        <div class="moto-list">
        <?php
        foreach ($data['locations'] as $location) {
            $moto = $location->getMoto();
            
        ?>
            <div class="moto-card">
                
                <p><?= $moto->getMarque(); ?> <?= $moto->getModele(); ?>
                 Début: <?= $location->getDebut() ?> Fin: <?= $location->getFin() ?></p>
            </div>
    <?php
        }
    }
    ?>
    </div>
</main>