<main>
    <h1><?= $data['moto']->getModele() ?></h1>
    
    <div class="motorcycle">
        <div class="motorcycle__info">
            <p>Marque: <?= $data['moto']->getMarque() ?></p>
            <p>Année: <?= $data['moto']->getAnnee() ?></p>
            <p>Description: <?= $data['moto']->getDescription() ?></p>
            <p>Prix: <?= $data['moto']->getPrix() ?> €</p>
        </div>

        <div class="motorcycle__image">
            <img src="<?= $data['moto']->getImage() ?>" alt="<?= $data['moto']->getModele() ?> Image" />
        </div>

        <div class="motorcycle__reservation">
            <a href="index.php?page=reservation&id=<?= $data['moto']->getId() ?>">Réservation</a>
        </div>
    </div>

    <?php if (isset($data['avis'])): ?>
        <?php foreach ($data['avis'] as $avis): ?>
            <?php $user = User::avisName($avis->getLocationId()); ?>
            <div class="review">
                <p>Auteur: <?= $user->getNom() ?></p>
                <p>Commentaire: <?= $avis->getCommentaire() ?></p>
                <p>Note: <?= $avis->getNote() ?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</main>
