
<nav>

    <ul id="menu">
		<li> <a href="index.php?page=accueil">Accueil</a></li>
		<li> <a href="index.php?page=formulaire_moto">Ajouter une moto</a></li>
	    <li> <a href="index.php?page=motos">Liste des motos</a></li>
		<li class="deroulant">Mon compte
			<ul class="sous">
				<li><a href="index.php?page=mes_motos">Mes Motos</a></li>
				<li><a href="index.php?page=mes_reservations">Mes Réservations</a></li>
				<li><a href="index.php?page=mes_locations">Mes Locations</a></li>
			</ul>
		</li>

	</ul>
 
 
</nav>

