<nav class="navbar">
    <div class="burger-menu">
        <div class="bar"></div>
        <div class="bar"></div>
        <div class="bar"></div>
    </div>
    <ul class="menu">
        <li><a href="index.php?page=accueil">Accueil</a></li>
        <li><a href="index.php?page=formulaire_moto">Ajouter une moto</a></li>
        <li><a href="index.php?page=motos">Liste des motos</a></li>
        <li class="deroulant">
            <a href="#">Mon compte</a>
            <ul class="sous">
                <li><a href="index.php?page=mes_motos">Mes Motos</a></li>
                <li><a href="index.php?page=mes_reservations">Mes locations</a></li>
                <li><a href="index.php?page=mes_locations">Mes motos louées</a></li>
                <?php if (userController::getAdmin()) : ?>
                <li><a href="index.php?page=administrateur">Administration du site</a></li>
                <?php endif; ?>
            </ul>
        </li>
    </ul>
</nav>