<main>
    <h1>Réservation</h1>

    <?php
    if (!empty($data['errors'])) {
    ?><ul><?php
                foreach ($data['errors'] as $error) {
                ?><li><?= $error ?></li><?php
            }
                ?></ul><?php
            }
                ?>
    <div class="reservations">

        <form class="reservation" method="POST">
            <label for="debut">Début:</label>
            <input type="date" id="debut" name="debut" required><br>

            <label for="fin">Fin:</label>
            <input type="date" id="fin" name="fin" required><br>

            <button name="submit">Réserver moto</button>
        </form>

        <form class="reservation" method="POST">

            <div class="calendar">
                <div class="header">
                    <button id="prevBtn" type="button">&lt;</button>
                    <div id="monthYear"></div>
                    <button id="nextBtn" type="button">&gt;</button>
                </div>

                <div class="days"></div>

            </div>
        </form>
    </div>
    <?php
    if (isset($data['locationMoto'])) {

    ?>
        <h2>Réservation pour cette moto</h2>
        <div class="affiche-resa">
            <?php
            foreach ($data['locationMoto'] as $locationMoto) {
                $moto = $locationMoto->getMoto();
            ?>
                <div class="moto-card">
                    <p><?= $moto->getMarque(); ?> <?= $moto->getModele(); ?>
                        Début: <?= $locationMoto->getDebutFormate() ?> Fin: <?= $locationMoto->getFinFormate() ?></p>
                </div><?php
                    }
                }
                        ?>
        </div>
</main>