<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vroom moto</title>
    <link rel="stylesheet" href="public/css/css.css" type="text/css" />
    <script type="text/javascript" src="public/js/main.js" defer></script>
    <script src="https://kit.fontawesome.com/581cc916c6.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Montserrat&family=Roboto:wght@100&display=swap" rel="stylesheet">
</head>

<body>

    <?php require_once "header.phtml"; ?>
    <?php require_once "nav.phtml"; ?>

    <?php
    if (isset($vue)) {
        require_once $vue;
    }
    ?>
    <?php require_once "footer.phtml"; ?>

</body>

</html>