<html lang="fr">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vroom moto</title>
    <link rel="stylesheet" href="public/css/css.css" type="text/css" />
    <script src="script.js"></script>
</head>

    <body>
        <?php require_once "header.phtml"; ?> 
        <?php require_once "nav.phtml"; ?>
        
<?php
    if (isset($vue)) {
        require_once $vue;
    }
?>
        <?php require_once "footer.phtml"; ?>
    </body>
</html>